//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExplorer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.SubDepartments = new HashSet<Department>();
            this.WorkersInDepartment = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Department> SubDepartments { get; set; }
        public virtual Department ParentDepartment { get; set; }
        public virtual ICollection<Client> WorkersInDepartment { get; set; }
    }
}
