//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExplorer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUser
    {
        public SiteUser()
        {
            this.News = new HashSet<News>();
            this.NewsComments = new HashSet<NewsComments>();
            this.TasksCreatedByUser = new HashSet<Task>();
            this.TasksForUser = new HashSet<Task>();
            this.TaskTimeCosts = new HashSet<TaskTimeCost>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Hash { get; set; }
        public string Login { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLocked { get; set; }
        public bool IsAdmin { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<NewsComments> NewsComments { get; set; }
        public virtual Client CompanyWorker { get; set; }
        public virtual SiteUserRole SiteUserRole { get; set; }
        public virtual ICollection<Task> TasksCreatedByUser { get; set; }
        public virtual ICollection<Task> TasksForUser { get; set; }
        public virtual ICollection<TaskTimeCost> TaskTimeCosts { get; set; }
    }
}
