//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExplorer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUserRole
    {
        public SiteUserRole()
        {
            this.SiteUser = new HashSet<SiteUser>();
        }
    
        public int Id { get; set; }
        public int RoleType { get; set; }
        public string RoleDescription { get; set; }
    
        public virtual ICollection<SiteUser> SiteUser { get; set; }
    }
}
