//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExplorer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTimeCost
    {
        public int Id { get; set; }
        public System.DateTime DbDateTime { get; set; }
        public decimal SpentHours { get; set; }
        public bool NeedToCheck { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual SiteUser TimeSpender { get; set; }
    }
}
