//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExplorer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskTimeCosts = new HashSet<TaskTimeCost>();
            this.TaskPerformers = new HashSet<SiteUser>();
            this.TaskClients = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> PlannedDateEnd { get; set; }
        public Nullable<decimal> PlannedTimeCost { get; set; }
        public bool NeedToCheck { get; set; }
    
        public virtual TaskTypes TaskType { get; set; }
        public virtual TastStates TastState { get; set; }
        public virtual ICollection<TaskTimeCost> TaskTimeCosts { get; set; }
        public virtual SiteUser TaskAuthor { get; set; }
        public virtual ICollection<SiteUser> TaskPerformers { get; set; }
        public virtual ICollection<Client> TaskClients { get; set; }
    }
}
