//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExplorer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TastStates
    {
        public TastStates()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string StateName { get; set; }
        public string StateDescription { get; set; }
    
        public virtual ICollection<Task> Task { get; set; }
    }
}
